#!/usr/bin/python3 -u
# Copyright (C) 2014 Bashton Ltd
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import hashlib
import os
import sys
import syslog
import urllib

import boto3
from configobj import ConfigObj


class APTMessage:
    MESSAGE_CODES = {
        100: 'Capabilities',
        102: 'Status',
        200: 'URI Start',
        201: 'URI Done',
        400: 'URI Failure',
        600: 'URI Acquire',
        601: 'Configuration',
    }

    def __init__(self, code, headers):
        self.code = code
        self.headers = headers

    def encode(self):
        result = '{0} {1}\n'.format(self.code, self.MESSAGE_CODES[self.code])
        for item in self.headers.keys():
            if self.headers[item] is not None:
                result += '{0}: {1}\n'.format(item, self.headers[item])
        return result + '\n'


class S3Method:
    __eof = False

    def __init__(self):
        config = self.__load_config()

        access_key = config['AccessKeyId']
        secret_key = config['SecretAccessKey']
        self.session = boto3.session.Session(aws_access_key_id=access_key,
                                             aws_secret_access_key=secret_key)
        self.s3 = self.session.resource('s3')
        self.send_capabilities()

    def __load_config(self):
        """
        Loading config file from predefined location.
        Example config file content:
            AccessKeyId = mykey
            SecretAccessKey = mysecretkey
            Token = '' # this can/have to be empty
        """
        _CONF_FILE = '/etc/apt/s3auth.conf'

        # Checking if 'file' exists, if it does read it
        if os.path.isfile(os.path.expanduser(_CONF_FILE)):
            config = ConfigObj(os.path.expanduser(_CONF_FILE))
            return config
        else:
            syslog.syslog("Config file: %s doesn't exist" % _CONF_FILE)
            raise Exception("Config file: %s doesn't exist" % _CONF_FILE)

    def fail(self, message='Failed'):
        self.send_uri_failure({'URI': self.uri, 'Message': message})

    def _read_message(self):
        """
        Apt uses for communication with its methods the text protocol similar
        to http. This function parses the protocol messages from stdin.
        """
        if self.__eof:
            return None
        result = {}
        line = sys.stdin.readline()
        while line == '\n':
            line = sys.stdin.readline()
        if not line:
            self.__eof = True
            return None
        s = line.split(" ", 1)
        result['_number'] = int(s[0])
        result['_text'] = s[1].strip()

        while not self.__eof:
            line = sys.stdin.readline()
            if not line:
                self.__eof = True
                return result
            if line == '\n':
                return result
            s = line.split(":", 1)
            result[s[0]] = s[1].strip()

    def send(self, code, headers):
        message = APTMessage(code, headers)
        syslog.syslog(message.encode())
        sys.stdout.write(message.encode())

    def send_capabilities(self):
        self.send(100, {'Version': '1.0', 'Single-Instance': 'true'})

    def send_status(self, headers):
        self.send(102, headers)

    def send_uri_start(self, headers):
        self.send(200, headers)

    def send_uri_done(self, headers):
        self.send(201, headers)

    def send_uri_failure(self, headers):
        self.send(400, headers)

    def run(self):
        """Loop through requests on stdin"""
        while True:
            message = self._read_message()
            if message is None:
                return 0
            if message['_number'] == 600:
                try:
                    self.fetch(message)
                except Exception as e:
                    self.fail(e.__class__.__name__ + ": " + str(e))
            else:
                return 100

    def fetch(self, msg):
        syslog.syslog(str(msg))
        self.uri = msg['URI']
        self.uri_parsed = urllib.parse.urlparse(self.uri)
        bucket = self.uri_parsed.netloc
        key = self.uri_parsed.path[1:]
        self.filename = msg['Filename']

        obj = self.s3.Object(bucket, key)
        self.send_status({'URI': self.uri, 'Message': 'Waiting for headers'})
        try:
            obj.load()
        except Exception as e:
            self.send_uri_failure({
                'URI': self.uri,
                'Message': str(e),
                'FailReason': str(e.response)})
            return

        self.send_uri_start({
            'URI': self.uri,
            'Size': obj.content_length,
            'Last-Modified': obj.last_modified})

        obj.download_file(self.filename)

        hash_sha256 = hashlib.sha256()
        hash_sha512 = hashlib.sha512()
        hash_md5 = hashlib.md5()

        with open(self.filename, 'rb') as f:
            hash_sha256 = hashlib.sha256()
            hash_sha512 = hashlib.sha512()
            hash_md5 = hashlib.md5()
            while True:
                data = f.read(4096)
                if not len(data):
                    break
                hash_sha256.update(data)
                hash_sha512.update(data)
                hash_md5.update(data)

        self.send_uri_done({
            'URI': self.uri,
            'Filename': self.filename,
            'Size': obj.content_length,
            'Last-Modified': obj.last_modified,
            'MD5-Hash': hash_md5.hexdigest(),
            'MD5Sum-Hash': hash_md5.hexdigest(),
            'SHA256-Hash': hash_sha256.hexdigest(),
            'SHA512-Hash': hash_sha512.hexdigest()})

if __name__ == '__main__':
    try:
        method = S3Method()
        ret = method.run()
        sys.exit(ret)
    except KeyboardInterrupt:
        pass
